# Generated by Django 5.0.4 on 2024-05-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_censorinfo_movieinfo_censor_detials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censorinfo',
            old_name='cirtfied_by',
            new_name='certified_by',
        ),
    ]
